### ISSUE TITLE
Python2 compatability broken

### ISSUE THREAD

**Issue by talwrii** [datacamp/antlr-ast#7]
```
>>> pip install antlr-ast; python -c   'import antlr4'
Collecting antlr-ast
Collecting antlr4-python3-runtime (from antlr-ast)
Installing collected packages: antlr4-python3-runtime, antlr-ast
Successfully installed antlr-ast-0.2.0 antlr4-python3-runtime-4.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/.local/lib/python2.7/site-packages/antlr4/__init__.py", line 1, in <mo
dule>
    from antlr4.Token import Token
  File "/home/tom/.local/lib/python2.7/site-packages/antlr4/Token.py", line 59
    def text(self, text:str):
                       ^
SyntaxError: invalid syntax
```

There is a question of whether you want to still support python2. Though one imagines you might want to more clearly exclude it.

This came up when working on latex2sympy.

**Comment by talwrii** [comment]
Whoops... this looks to be an issue in `antlr4-python3-runtime` that you import. 
closing the issue.

**Comment by talwrii** [comment]
Nope, untaken back. You should be depending on an appropriate version like so:

```
if sys.version_info.major == 3:
    REQUIRES = ['antlr4-python3-runtime',  'sympy']
else:
    REQUIRES = ['antlr4-python2-runtime',  'sympy']
```

or excluding python2 or python3 as appropriate.

**Comment by machow** [comment]
Hey @talwrii that's a good point. Currently, I've been focused on getting basic features up, so haven't thought too much about Python2 compatibility. It seems like there are a couple things that would need to change

* the requirement on the antlr-runtime you mentioned
* small antlr parser in `tests/`, generated using python3 target
* possibly some cases using backward incompatible syntax (should be few)

Should be pretty quick to make, I'll try to take a pass over it in the next few weeks.
